services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image : chatr
    container_name: app
    depends_on:
      - broker
      - database
    environment:
      SPRING_MAIL_DOMAIN: domain
      SPRING_MAIL_HOST: host
      SPRING_MAIL_PASSWORD: password
      SPRING_MAIL_USERNAME: username
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/CHATR
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_TOKEN_SECRET: L8vJh5TDoBFOG7QXWRh3zqf3Ib0BdsFt5SHXSaOkq90=

    ports:
      - "8080:8080"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  broker:
      image: confluentinc/cp-kafka:7.4.4
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: CHATR
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password






